# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mjc284/Documents/Work/mjc284_glfw_exploration

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mjc284/Documents/Work/mjc284_glfw_exploration

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mjc284/Documents/Work/mjc284_glfw_exploration/CMakeFiles /home/mjc284/Documents/Work/mjc284_glfw_exploration//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mjc284/Documents/Work/mjc284_glfw_exploration/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named particles

# Build rule for target.
particles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 particles
.PHONY : particles

# fast build rule for target.
particles/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particles.dir/build.make CMakeFiles/particles.dir/build
.PHONY : particles/fast

#=============================================================================
# Target rules for targets named mandelbrot

# Build rule for target.
mandelbrot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mandelbrot
.PHONY : mandelbrot

# fast build rule for target.
mandelbrot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelbrot.dir/build.make CMakeFiles/mandelbrot.dir/build
.PHONY : mandelbrot/fast

#=============================================================================
# Target rules for targets named dimensions

# Build rule for target.
dimensions: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dimensions
.PHONY : dimensions

# fast build rule for target.
dimensions/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dimensions.dir/build.make CMakeFiles/dimensions.dir/build
.PHONY : dimensions/fast

#=============================================================================
# Target rules for targets named box

# Build rule for target.
box: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 box
.PHONY : box

# fast build rule for target.
box/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/box.dir/build.make CMakeFiles/box.dir/build
.PHONY : box/fast

#=============================================================================
# Target rules for targets named planets_orbit

# Build rule for target.
planets_orbit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 planets_orbit
.PHONY : planets_orbit

# fast build rule for target.
planets_orbit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_orbit.dir/build.make CMakeFiles/planets_orbit.dir/build
.PHONY : planets_orbit/fast

#=============================================================================
# Target rules for targets named planets_random

# Build rule for target.
planets_random: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 planets_random
.PHONY : planets_random

# fast build rule for target.
planets_random/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_random.dir/build.make CMakeFiles/planets_random.dir/build
.PHONY : planets_random/fast

#=============================================================================
# Target rules for targets named planets_uniform

# Build rule for target.
planets_uniform: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 planets_uniform
.PHONY : planets_uniform

# fast build rule for target.
planets_uniform/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_uniform.dir/build.make CMakeFiles/planets_uniform.dir/build
.PHONY : planets_uniform/fast

glad/src/glad.o: glad/src/glad.c.o
.PHONY : glad/src/glad.o

# target to build an object file
glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particles.dir/build.make CMakeFiles/particles.dir/glad/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelbrot.dir/build.make CMakeFiles/mandelbrot.dir/glad/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dimensions.dir/build.make CMakeFiles/dimensions.dir/glad/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/box.dir/build.make CMakeFiles/box.dir/glad/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_orbit.dir/build.make CMakeFiles/planets_orbit.dir/glad/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_random.dir/build.make CMakeFiles/planets_random.dir/glad/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_uniform.dir/build.make CMakeFiles/planets_uniform.dir/glad/src/glad.c.o
.PHONY : glad/src/glad.c.o

glad/src/glad.i: glad/src/glad.c.i
.PHONY : glad/src/glad.i

# target to preprocess a source file
glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particles.dir/build.make CMakeFiles/particles.dir/glad/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelbrot.dir/build.make CMakeFiles/mandelbrot.dir/glad/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dimensions.dir/build.make CMakeFiles/dimensions.dir/glad/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/box.dir/build.make CMakeFiles/box.dir/glad/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_orbit.dir/build.make CMakeFiles/planets_orbit.dir/glad/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_random.dir/build.make CMakeFiles/planets_random.dir/glad/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_uniform.dir/build.make CMakeFiles/planets_uniform.dir/glad/src/glad.c.i
.PHONY : glad/src/glad.c.i

glad/src/glad.s: glad/src/glad.c.s
.PHONY : glad/src/glad.s

# target to generate assembly for a file
glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particles.dir/build.make CMakeFiles/particles.dir/glad/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelbrot.dir/build.make CMakeFiles/mandelbrot.dir/glad/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dimensions.dir/build.make CMakeFiles/dimensions.dir/glad/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/box.dir/build.make CMakeFiles/box.dir/glad/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_orbit.dir/build.make CMakeFiles/planets_orbit.dir/glad/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_random.dir/build.make CMakeFiles/planets_random.dir/glad/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_uniform.dir/build.make CMakeFiles/planets_uniform.dir/glad/src/glad.c.s
.PHONY : glad/src/glad.c.s

src/box.o: src/box.cpp.o
.PHONY : src/box.o

# target to build an object file
src/box.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/box.dir/build.make CMakeFiles/box.dir/src/box.cpp.o
.PHONY : src/box.cpp.o

src/box.i: src/box.cpp.i
.PHONY : src/box.i

# target to preprocess a source file
src/box.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/box.dir/build.make CMakeFiles/box.dir/src/box.cpp.i
.PHONY : src/box.cpp.i

src/box.s: src/box.cpp.s
.PHONY : src/box.s

# target to generate assembly for a file
src/box.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/box.dir/build.make CMakeFiles/box.dir/src/box.cpp.s
.PHONY : src/box.cpp.s

src/dimensions.o: src/dimensions.cpp.o
.PHONY : src/dimensions.o

# target to build an object file
src/dimensions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dimensions.dir/build.make CMakeFiles/dimensions.dir/src/dimensions.cpp.o
.PHONY : src/dimensions.cpp.o

src/dimensions.i: src/dimensions.cpp.i
.PHONY : src/dimensions.i

# target to preprocess a source file
src/dimensions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dimensions.dir/build.make CMakeFiles/dimensions.dir/src/dimensions.cpp.i
.PHONY : src/dimensions.cpp.i

src/dimensions.s: src/dimensions.cpp.s
.PHONY : src/dimensions.s

# target to generate assembly for a file
src/dimensions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dimensions.dir/build.make CMakeFiles/dimensions.dir/src/dimensions.cpp.s
.PHONY : src/dimensions.cpp.s

src/mandelbrot.o: src/mandelbrot.cpp.o
.PHONY : src/mandelbrot.o

# target to build an object file
src/mandelbrot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelbrot.dir/build.make CMakeFiles/mandelbrot.dir/src/mandelbrot.cpp.o
.PHONY : src/mandelbrot.cpp.o

src/mandelbrot.i: src/mandelbrot.cpp.i
.PHONY : src/mandelbrot.i

# target to preprocess a source file
src/mandelbrot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelbrot.dir/build.make CMakeFiles/mandelbrot.dir/src/mandelbrot.cpp.i
.PHONY : src/mandelbrot.cpp.i

src/mandelbrot.s: src/mandelbrot.cpp.s
.PHONY : src/mandelbrot.s

# target to generate assembly for a file
src/mandelbrot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelbrot.dir/build.make CMakeFiles/mandelbrot.dir/src/mandelbrot.cpp.s
.PHONY : src/mandelbrot.cpp.s

src/particles.o: src/particles.cpp.o
.PHONY : src/particles.o

# target to build an object file
src/particles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particles.dir/build.make CMakeFiles/particles.dir/src/particles.cpp.o
.PHONY : src/particles.cpp.o

src/particles.i: src/particles.cpp.i
.PHONY : src/particles.i

# target to preprocess a source file
src/particles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particles.dir/build.make CMakeFiles/particles.dir/src/particles.cpp.i
.PHONY : src/particles.cpp.i

src/particles.s: src/particles.cpp.s
.PHONY : src/particles.s

# target to generate assembly for a file
src/particles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particles.dir/build.make CMakeFiles/particles.dir/src/particles.cpp.s
.PHONY : src/particles.cpp.s

src/planets/planets_orbit.o: src/planets/planets_orbit.cpp.o
.PHONY : src/planets/planets_orbit.o

# target to build an object file
src/planets/planets_orbit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_orbit.dir/build.make CMakeFiles/planets_orbit.dir/src/planets/planets_orbit.cpp.o
.PHONY : src/planets/planets_orbit.cpp.o

src/planets/planets_orbit.i: src/planets/planets_orbit.cpp.i
.PHONY : src/planets/planets_orbit.i

# target to preprocess a source file
src/planets/planets_orbit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_orbit.dir/build.make CMakeFiles/planets_orbit.dir/src/planets/planets_orbit.cpp.i
.PHONY : src/planets/planets_orbit.cpp.i

src/planets/planets_orbit.s: src/planets/planets_orbit.cpp.s
.PHONY : src/planets/planets_orbit.s

# target to generate assembly for a file
src/planets/planets_orbit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_orbit.dir/build.make CMakeFiles/planets_orbit.dir/src/planets/planets_orbit.cpp.s
.PHONY : src/planets/planets_orbit.cpp.s

src/planets/planets_random.o: src/planets/planets_random.cpp.o
.PHONY : src/planets/planets_random.o

# target to build an object file
src/planets/planets_random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_random.dir/build.make CMakeFiles/planets_random.dir/src/planets/planets_random.cpp.o
.PHONY : src/planets/planets_random.cpp.o

src/planets/planets_random.i: src/planets/planets_random.cpp.i
.PHONY : src/planets/planets_random.i

# target to preprocess a source file
src/planets/planets_random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_random.dir/build.make CMakeFiles/planets_random.dir/src/planets/planets_random.cpp.i
.PHONY : src/planets/planets_random.cpp.i

src/planets/planets_random.s: src/planets/planets_random.cpp.s
.PHONY : src/planets/planets_random.s

# target to generate assembly for a file
src/planets/planets_random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_random.dir/build.make CMakeFiles/planets_random.dir/src/planets/planets_random.cpp.s
.PHONY : src/planets/planets_random.cpp.s

src/planets/planets_uniform.o: src/planets/planets_uniform.cpp.o
.PHONY : src/planets/planets_uniform.o

# target to build an object file
src/planets/planets_uniform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_uniform.dir/build.make CMakeFiles/planets_uniform.dir/src/planets/planets_uniform.cpp.o
.PHONY : src/planets/planets_uniform.cpp.o

src/planets/planets_uniform.i: src/planets/planets_uniform.cpp.i
.PHONY : src/planets/planets_uniform.i

# target to preprocess a source file
src/planets/planets_uniform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_uniform.dir/build.make CMakeFiles/planets_uniform.dir/src/planets/planets_uniform.cpp.i
.PHONY : src/planets/planets_uniform.cpp.i

src/planets/planets_uniform.s: src/planets/planets_uniform.cpp.s
.PHONY : src/planets/planets_uniform.s

# target to generate assembly for a file
src/planets/planets_uniform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/planets_uniform.dir/build.make CMakeFiles/planets_uniform.dir/src/planets/planets_uniform.cpp.s
.PHONY : src/planets/planets_uniform.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... box"
	@echo "... dimensions"
	@echo "... mandelbrot"
	@echo "... particles"
	@echo "... planets_orbit"
	@echo "... planets_random"
	@echo "... planets_uniform"
	@echo "... glad/src/glad.o"
	@echo "... glad/src/glad.i"
	@echo "... glad/src/glad.s"
	@echo "... src/box.o"
	@echo "... src/box.i"
	@echo "... src/box.s"
	@echo "... src/dimensions.o"
	@echo "... src/dimensions.i"
	@echo "... src/dimensions.s"
	@echo "... src/mandelbrot.o"
	@echo "... src/mandelbrot.i"
	@echo "... src/mandelbrot.s"
	@echo "... src/particles.o"
	@echo "... src/particles.i"
	@echo "... src/particles.s"
	@echo "... src/planets/planets_orbit.o"
	@echo "... src/planets/planets_orbit.i"
	@echo "... src/planets/planets_orbit.s"
	@echo "... src/planets/planets_random.o"
	@echo "... src/planets/planets_random.i"
	@echo "... src/planets/planets_random.s"
	@echo "... src/planets/planets_uniform.o"
	@echo "... src/planets/planets_uniform.i"
	@echo "... src/planets/planets_uniform.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

